baseURL: "http://donvictor13.github.io/"
title: donvictor.dev
paginate: 5
theme: PaperMod
languageCode: 'en-us'

params:
    profileMode:
        enabled: true
        title: "Don Victor" # optional default will be site title
        subtitle: "Hi, I am an Devops engineer and technology enthusiast."
        imageUrl: "https://avatars.githubusercontent.com/u/33443934?v=4"
  	buttons:
         - name: Email
           url: "mailto:contact@donvictor.dev"  

    socialIcons:
      - name: github
        url: "https://github.com/donvictor13"
      

